######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 26 03:07:47 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QTWindow.h
SOURCES += main.cpp QTWindow.cpp
