######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 2 02:05:06 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CVMath.h Points.h QTWindow.h
SOURCES += CVMath.cpp main.cpp Points.cpp QTWindow.cpp
