######################################################################
# Automatically generated by qmake (2.01a) dom ago 2 17:35:57 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CVMath.h Points.h QTWindow.h
SOURCES += CVMath.cpp main.cpp Points.cpp QTWindow.cpp
