######################################################################
# Automatically generated by qmake (2.01a) qui set 24 00:59:10 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Image.h Utils.h
SOURCES += image.cpp main.cpp Utils.cpp
