######################################################################
# Automatically generated by qmake (2.01a) qui set 17 23:25:13 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Utils.h
SOURCES += main.cpp Utils.cpp
