######################################################################
# Automatically generated by qmake (2.01a) ter out 6 00:01:44 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Utils.h
SOURCES += main.cpp Utils.cpp
